import { useMemo, useState, type FormEvent } from "react";
import { FileInput, Plus, Trash2, X } from "lucide-react";
import { BulkStockImport, Resource } from "../types";

type Line = { key: number; resourceId: string; quantity: number; totalPrice: number };
const today = () => new Date().toISOString().slice(0, 10);

export default function BulkStockImportModal({ resources, onImport, onClose }: { resources: Resource[]; onImport: (data: BulkStockImport) => Promise<void>; onClose: () => void }) {
  const available = useMemo(() => resources.filter((item) => item.bundle === "condiment" || item.bundle === "ambalaj").sort((a, b) => a.label.localeCompare(b.label)), [resources]);
  const first = available[0];
  const createLine = (key: number): Line => ({ key, resourceId: first?.id || "", quantity: 1, totalPrice: first?.currentPrice || 0 });
  const [lines, setLines] = useState<Line[]>([createLine(Date.now())]);
  const [date, setDate] = useState(today());
  const [reference, setReference] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const total = lines.reduce((sum, line) => sum + line.totalPrice, 0);
  const update = (key: number, fields: Partial<Line>) => setLines((current) => current.map((line) => line.key === key ? { ...line, ...fields } : line));
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setBusy(true);
    try { setError(""); await onImport({ date, source: reference.trim() ? `Aprovizionare multiplă: ${reference.trim()}` : "Aprovizionare multiplă", items: lines.map(({ resourceId, quantity, totalPrice }) => ({ resourceId, quantity, totalPrice })) }); onClose(); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Importul nu a putut fi salvat."); }
    finally { setBusy(false); }
  };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-stone-950/80 p-4 backdrop-blur-sm"><form onSubmit={submit} className="max-h-[94vh] w-full max-w-5xl overflow-y-auto rounded-xl border border-amber-900/30 bg-stone-900 p-6 shadow-2xl"><div className="mb-5 flex items-start justify-between border-b border-stone-800 pb-4"><div><h3 className="flex items-center gap-2 text-xl font-bold"><FileInput className="text-amber-500" />Importă mai multe produse</h3><p className="mt-1 text-sm text-stone-400">Toate pozițiile vor fi salvate împreună ca loturi FIFO.</p></div><button type="button" onClick={onClose} aria-label="Închide" className="rounded p-2 hover:bg-stone-800"><X /></button></div>
    <div className="mb-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Data achiziției<input required type="date" value={date} onChange={(event) => setDate(event.target.value)} className="mt-2 h-12 w-full rounded-lg border border-stone-700 bg-stone-950 px-3" /></label><label className="text-sm font-semibold">Factură / furnizor / notă<input value={reference} onChange={(event) => setReference(event.target.value)} placeholder="Ex: Factura 125, Furnizor SRL" className="mt-2 h-12 w-full rounded-lg border border-stone-700 bg-stone-950 px-3" /></label></div>
    <div className="space-y-3">{lines.map((line, index) => { const resource = available.find((item) => item.id === line.resourceId); const priceUnit = line.quantity > 0 ? line.totalPrice / line.quantity : 0; return <div key={line.key} className="relative grid items-end gap-3 rounded-xl border border-stone-800 bg-stone-950/40 p-4 pr-16 md:grid-cols-[2fr_1fr_1fr_1fr]"><label className="text-xs font-semibold text-stone-400">Produs<select required value={line.resourceId} onChange={(event) => { const selected = available.find((item) => item.id === event.target.value); update(line.key, { resourceId: event.target.value, totalPrice: selected?.currentPrice || 0 }); }} className="mt-2 h-11 w-full rounded-lg border border-stone-700 bg-stone-950 px-3 text-sm">{available.map((item) => <option key={item.id} value={item.id}>{item.bundle === "ambalaj" ? "Ambalaj" : "Condiment"} · {item.label}</option>)}</select></label><label className="text-xs font-semibold text-stone-400">Cantitate ({resource?.unit || "unități"})<span className="mt-2 flex h-11 items-center rounded-lg border border-stone-700 bg-stone-950"><input required min="0.0001" step="0.0001" type="number" value={line.quantity} onChange={(event) => update(line.key, { quantity: Number(event.target.value) })} className="h-full min-w-0 flex-1 bg-transparent px-3 text-right outline-none" /><b className="border-l border-stone-700 px-3 text-amber-500">{resource?.unit}</b></span></label><label className="text-xs font-semibold text-stone-400">Suma totală plătită<input required min="0" step="0.01" type="number" value={line.totalPrice} onChange={(event) => update(line.key, { totalPrice: Number(event.target.value) })} className="mt-2 h-11 w-full rounded-lg border border-stone-700 bg-stone-950 px-3 text-right" /></label><div><small className="block h-5 font-semibold text-stone-400">Preț calculat / {resource?.unit}</small><b className="flex h-11 items-center justify-end whitespace-nowrap text-amber-500">{priceUnit.toFixed(4)} L/{resource?.unit}</b></div><button type="button" disabled={lines.length === 1} onClick={() => setLines((current) => current.filter((item) => item.key !== line.key))} title={`Șterge poziția ${index + 1}`} className="absolute right-3 top-4 grid h-11 w-11 place-items-center rounded-lg text-red-400 hover:bg-red-950/30 disabled:opacity-30"><Trash2 className="h-5 w-5" /></button></div>; })}</div>
    {!available.length && <p className="rounded-lg bg-red-950/30 p-4 text-red-300">Creați mai întâi cel puțin un condiment sau ambalaj.</p>}{error && <p className="mt-4 rounded-lg bg-red-950/30 p-4 text-red-300">{error}</p>}
    <button type="button" disabled={!available.length} onClick={() => setLines((current) => [...current, createLine(Date.now() + current.length)])} className="mt-4 flex h-11 items-center gap-2 rounded-lg border border-amber-700 px-4 font-bold text-amber-500"><Plus className="h-5 w-5" />Adaugă încă un produs</button>
    <div className="mt-6 flex flex-wrap items-center justify-between gap-4 border-t border-stone-800 pt-5"><div><small className="text-stone-500">Total import · {lines.length} poziții</small><p className="text-2xl font-bold text-amber-500">{total.toFixed(2)} L</p></div><div className="flex gap-3"><button type="button" onClick={onClose} className="h-12 rounded-lg px-5 font-bold">Renunță</button><button disabled={busy || !available.length} className="h-12 rounded-lg bg-amber-600 px-6 font-bold text-stone-950">{busy ? "Se importă…" : "Importă toate produsele"}</button></div></div></form></div>;
}
