import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, ArrowLeft, ArrowRight, BookOpen, Calculator, CheckCircle2, ChevronRight, CircleHelp, FileSpreadsheet, Handshake, Lightbulb, List, Package, Search, ScrollText, ShieldCheck, ShoppingCart, Users, Warehouse, X } from "lucide-react";

type Language = "ro" | "ru";
type L = { ro: string; ru: string };
type IconName = "start" | "dashboard" | "calculator" | "recipes" | "lots" | "partners" | "sales" | "stock" | "staff" | "products" | "reports" | "update" | "formulas" | "problems";
type Formula = { name: L; formula: L; example: L };
type Section = { id: string; icon: IconName; title: L; summary: L; steps?: L[]; notes?: L[]; warning?: L; formulas?: Formula[] };

const l = (ro: string, ru: string): L => ({ ro, ru });
const tr = (value: L, language: Language) => value[language];

const sections: Section[] = [
  { id: "inceput", icon: "start", title: l("Început rapid", "Быстрое начало"), summary: l("Programul păstrează evidența rețetelor, stocurilor, loturilor, partenerilor și vânzărilor. Începeți cu resursele și prețurile lor, apoi creați rețetele și produsele.", "Программа ведёт учёт рецептов, запасов, партий, партнёров и продаж. Сначала внесите ресурсы и цены, затем создайте рецепты и продукты."), steps: [l("Autentificați-vă cu numele și parola primite de la administrator.", "Войдите с именем и паролем, полученными от администратора."), l("Introduceți Materia primă, Condimentele și Alte cheltuieli.", "Внесите Сырьё, Специи и Прочие расходы."), l("Creați rețetele, apoi legați fiecare produs de rețeta lui.", "Создайте рецепты и свяжите каждый продукт с его рецептом."), l("Folosiți Calculatorul pentru planificare sau Loturile pentru producția reală.", "Для планирования используйте Калькулятор, для реального производства — Партии.")], notes: [l("Butonul soare/lună schimbă tema de zi sau noapte.", "Кнопка солнце/луна меняет дневную и ночную тему."), l("Datele se păstrează numai după apăsarea butonului Salvează sau Adaugă.", "Данные сохраняются только после нажатия Сохранить или Добавить.")] },
  { id: "principala", icon: "dashboard", title: l("Pagina principală", "Главная страница"), summary: l("Aici vedeți situația generală: producția, veniturile, cheltuielile, rezultatul și activitatea recentă. Perioada aleasă schimbă totalurile afișate.", "Здесь показана общая ситуация: производство, доходы, расходы, результат и последние операции. Выбранный период изменяет итоги."), steps: [l("Alegeți perioada pe care doriți să o analizați.", "Выберите период для анализа."), l("Citiți totalurile de sus, apoi graficul și tabelul operațiilor.", "Сначала прочитайте верхние итоги, затем график и таблицу операций."), l("Deschideți modulul dorit din meniul de sus pentru detalii.", "Для подробностей откройте нужный раздел верхнего меню.")], warning: l("Pagina principală nu schimbă datele; ea rezumă operațiile salvate în celelalte module.", "Главная страница не изменяет данные; она обобщает операции из других разделов.") },
  { id: "calculator", icon: "calculator", title: l("Calculatorul de producție", "Производственный калькулятор"), summary: l("Calculatorul arată ingredientele necesare și costul unei cantități planificate. El nu scade nimic din stoc.", "Калькулятор показывает нужные ингредиенты и стоимость планируемого объёма. Он ничего не списывает со склада."), steps: [l("Alegeți produsul sau rețeta.", "Выберите продукт или рецепт."), l("Introduceți cantitatea pe care doriți să o produceți.", "Введите количество, которое хотите произвести."), l("Verificați materia primă, condimentele, subrețetele, cheltuielile și manopera.", "Проверьте сырьё, специи, подрецепты, расходы и работу."), l("Citiți costul total, costul pe unitate și prețul recomandat.", "Посмотрите общую стоимость, стоимость единицы и рекомендуемую цену.")], notes: [l("Cantitate necesară = cantitatea din rețetă × cantitatea planificată.", "Нужное количество = количество в рецепте × планируемый объём.")] },
  { id: "retete", icon: "recipes", title: l("Rețete și subrețete", "Рецепты и подрецепты"), summary: l("O rețetă combină materii prime, condimente, cheltuieli, manoperă și subrețete. O subrețetă este un amestec reutilizabil, de exemplu saramura.", "Рецепт объединяет сырьё, специи, расходы, работу и подрецепты. Подрецепт — повторно используемая смесь, например рассол."), steps: [l("Apăsați Adaugă rețetă și scrieți denumirea și unitatea de bază.", "Нажмите Добавить рецепт, укажите название и базовую единицу."), l("Adăugați componentele și cantitatea pentru o unitate de bază.", "Добавьте компоненты и количество на одну базовую единицу."), l("Creați saramura ca subrețetă înainte de a o adăuga în rețeta principală.", "Создайте рассол как подрецепт перед добавлением в основной рецепт."), l("Verificați costul calculat și salvați.", "Проверьте рассчитанную стоимость и сохраните.")], warning: l("O rețetă nu poate să se includă pe ea însăși, nici prin alte subrețete. Programul blochează asemenea cercuri.", "Рецепт не может включать сам себя, даже через другие подрецепты. Программа блокирует такие циклы.") },
  { id: "loturi", icon: "lots", title: l("Loturi de producție", "Производственные партии"), summary: l("Lotul este o producție reală, cu dată, cantitate intrată, cantitate obținută, ingrediente și costuri. Poate fi producție proprie sau procesarea materiei clientului.", "Партия — реальное производство с датой, входным и полученным количеством, ингредиентами и расходами. Это может быть собственное производство или переработка сырья клиента."), steps: [l("Apăsați Lot nou și alegeți tipul producției.", "Нажмите Новая партия и выберите тип производства."), l("Alegeți produsul, rețeta și, pentru procesare, partenerul.", "Выберите продукт, рецепт и, для переработки, партнёра."), l("Introduceți cantitatea de intrare; rețeta este extinsă automat.", "Введите входное количество; рецепт развернётся автоматически."), l("La sfârșit introduceți cantitatea obținută și finalizați lotul.", "В конце укажите полученное количество и завершите партию.")], warning: l("Finalizarea poate consuma stoc și crea produs finit, încasări sau datorii. Verificați cantitățile înainte de confirmare.", "Завершение может списать запас и создать готовый продукт, оплату или долг. Проверьте количества перед подтверждением.") },
  { id: "parteneri", icon: "partners", title: l("Parteneri și decontări", "Партнёры и расчёты"), summary: l("Partenerul poate fi client, furnizor sau ambele. Fișa lui reunește loturile, sumele datorate, plățile și soldul.", "Партнёр может быть клиентом, поставщиком или обоими. Его карточка объединяет партии, начисления, платежи и остаток."), steps: [l("Adăugați denumirea partenerului și rolul său.", "Добавьте название партнёра и его роль."), l("Selectați partenerul corect în loturile pentru client.", "Выберите правильного партнёра в партиях клиента."), l("Înregistrați plata numai după primirea sau achitarea banilor.", "Регистрируйте платёж только после получения или выплаты денег."), l("Verificați extrasul: datorat minus plătit este soldul.", "Проверьте выписку: начислено минус оплачено равно остатку.")] },
  { id: "vanzari", icon: "sales", title: l("Vânzări și retururi", "Продажи и возвраты"), summary: l("La vânzare, programul scade produsul din cele mai vechi loturi și calculează costul real FIFO și profitul.", "При продаже программа списывает продукт из самых старых партий и рассчитывает фактическую стоимость FIFO и прибыль."), steps: [l("Alegeți produsul, data, cantitatea și prețul pe unitate.", "Выберите продукт, дату, количество и цену единицы."), l("Verificați calculul FIFO, stocul după vânzare și profitul.", "Проверьте расчёт FIFO, остаток после продажи и прибыль."), l("Pentru retur deschideți vânzarea originală și indicați cantitatea.", "Для возврата откройте исходную продажу и укажите количество."), l("Bifați Brac dacă produsul deteriorat nu trebuie întors în stoc.", "Отметьте Брак, если повреждённый товар не должен возвращаться на склад.")], warning: l("Returul nu poate depăși cantitatea vândută rămasă, iar data lui nu poate fi înaintea vânzării.", "Возврат не может превышать оставшееся проданное количество, а его дата не может быть раньше продажи.") },
  { id: "stocuri", icon: "stock", title: l("Materii prime, condimente și cheltuieli", "Сырьё, специи и расходы"), summary: l("Aceste module formează catalogul de resurse. Prețul curent intră în rețete, iar recepțiile creează loturi de stoc la costul lor real.", "Эти разделы образуют каталог ресурсов. Текущая цена входит в рецепты, а поступления создают складские партии по фактической стоимости."), steps: [l("Adăugați denumirea, unitatea corectă și prețul curent.", "Добавьте название, правильную единицу и текущую цену."), l("Înregistrați intrarea cu data, cantitatea și prețul unitar.", "Зарегистрируйте поступление с датой, количеством и ценой единицы."), l("Nu schimbați unitatea unei resurse folosite fără verificarea rețetelor.", "Не меняйте единицу используемого ресурса без проверки рецептов."), l("Folosiți importul în masă pentru mai multe poziții din aceeași factură.", "Используйте массовый импорт для нескольких позиций одной накладной.")] },
  { id: "personal", icon: "staff", title: l("Munca personalului", "Работа персонала"), summary: l("Fiecare angajat poate avea tarife diferite pe rețete. Manopera intră în cost când angajatul este adăugat în rețetă.", "У каждого работника могут быть разные тарифы по рецептам. Работа входит в стоимость, когда работник добавлен в рецепт."), steps: [l("Adăugați angajatul și funcția lui.", "Добавьте работника и его должность."), l("Introduceți tariful pentru rețetele la care lucrează.", "Укажите тариф для рецептов, над которыми он работает."), l("În rețetă adăugați linia Manoperă, angajatul și cantitatea.", "В рецепте добавьте строку Работа, работника и количество.")] },
  { id: "produse", icon: "products", title: l("Produse finale", "Готовая продукция"), summary: l("Produsul final leagă denumirea comercială de rețetă, unitate, stoc și preț. Producția finalizată îi mărește stocul; vânzarea îl micșorează.", "Готовый продукт связывает торговое название с рецептом, единицей, запасом и ценой. Завершённое производство увеличивает запас, продажа уменьшает."), steps: [l("Adăugați produsul și selectați rețeta corectă.", "Добавьте продукт и выберите правильный рецепт."), l("Verificați unitatea și prețul de vânzare.", "Проверьте единицу и цену продажи."), l("Nu introduceți manual stocul produs; finalizați lotul corespunzător.", "Не вводите запас продукта вручную; завершите соответствующую партию.")] },
  { id: "rapoarte", icon: "reports", title: l("Rapoarte și istoric", "Отчёты и история"), summary: l("Rapoartele compară intrarea cu ieșirea și arată pierderea, costul real, venitul și profitul. Istoricul păstrează operațiile salvate.", "Отчёты сравнивают вход и выход, показывают потери, фактическую стоимость, доход и прибыль. История хранит сохранённые операции."), steps: [l("Alegeți perioada și produsul sau partenerul, dacă este disponibil.", "Выберите период и продукт или партнёра, если доступно."), l("Comparați cantitatea intrată, ieșită și procentul pierderii.", "Сравните входное, выходное количество и процент потерь."), l("Comparați venitul cu toate costurile, nu doar cu materia primă.", "Сравнивайте доход со всеми расходами, а не только с сырьём.")] },
  { id: "actualizare", icon: "update", title: l("Actualizarea aplicației Windows", "Обновление приложения Windows"), summary: l("Butonul cu săgeți circulare verifică dacă există o versiune nouă. Varianta WEB este actualizată pe server.", "Кнопка с круговыми стрелками проверяет новую версию. WEB-версия обновляется на сервере."), steps: [l("Salvați operația la care lucrați.", "Сохраните текущую операцию."), l("Apăsați Actualizare și așteptați verificarea.", "Нажмите Обновление и дождитесь проверки."), l("Confirmați versiunea nouă și nu închideți programul în timpul instalării.", "Подтвердите новую версию и не закрывайте программу во время установки.")] },
  { id: "calcule", icon: "formulas", title: l("Cum se fac calculele", "Как выполняются расчёты"), summary: l("Serverul validează definitiv stocurile, vânzările și loturile. Previzualizarea din interfață vă permite să verificați rezultatul înainte de salvare.", "Сервер окончательно проверяет запасы, продажи и партии. Предварительный расчёт позволяет проверить результат до сохранения."), formulas: [
    { name: l("Cost linie de rețetă", "Стоимость строки рецепта"), formula: l("preț unitar × cantitate", "цена единицы × количество"), example: l("2 kg sare × 8 Lei/kg = 16 Lei", "2 кг соли × 8 Lei/кг = 16 Lei") },
    { name: l("Cost total rețetă", "Общая стоимость рецепта"), formula: l("materii + condimente + subrețete + cheltuieli + manoperă", "сырьё + специи + подрецепты + расходы + работа"), example: l("100 + 20 + 15 + 10 + 30 = 175 Lei", "100 + 20 + 15 + 10 + 30 = 175 Lei") },
    { name: l("Cantitate necesară", "Нужное количество"), formula: l("cantitate în rețetă × producția planificată", "количество в рецепте × план производства"), example: l("0,020 kg sare × 50 kg = 1 kg", "0,020 кг соли × 50 кг = 1 кг") },
    { name: l("Cost intrare", "Стоимость входа"), formula: l("cantitate intrată × cost rețetă/unitate", "входное количество × стоимость рецепта/ед."), example: l("10 kg × 80 Lei/kg = 800 Lei", "10 кг × 80 Lei/кг = 800 Lei") },
    { name: l("Randament", "Выход"), formula: l("ieșire ÷ intrare × 100", "выход ÷ вход × 100"), example: l("8 kg ÷ 10 kg × 100 = 80%", "8 кг ÷ 10 кг × 100 = 80%") },
    { name: l("Pierdere", "Потери"), formula: l("(intrare − ieșire) ÷ intrare × 100", "(вход − выход) ÷ вход × 100"), example: l("(10 − 8) ÷ 10 × 100 = 20%", "(10 − 8) ÷ 10 × 100 = 20%") },
    { name: l("Cost real/kg ieșire", "Стоимость/кг выхода"), formula: l("cost total intrare ÷ cantitate ieșită", "общая стоимость входа ÷ выходное количество"), example: l("800 Lei ÷ 8 kg = 100 Lei/kg", "800 Lei ÷ 8 кг = 100 Lei/кг") },
    { name: l("Preț recomandat", "Рекомендуемая цена"), formula: l("cost unitar × (1 + adaos% ÷ 100)", "стоимость ед. × (1 + наценка% ÷ 100)"), example: l("100 × (1 + 70 ÷ 100) = 170 Lei", "100 × (1 + 70 ÷ 100) = 170 Lei") },
    { name: l("Venit și profit", "Доход и прибыль"), formula: l("venit = cantitate × preț; profit = venit − cost FIFO", "доход = количество × цена; прибыль = доход − FIFO"), example: l("5 × 170 = 850; 850 − 500 = 350 Lei", "5 × 170 = 850; 850 − 500 = 350 Lei") },
    { name: l("Serviciu pentru client", "Услуга клиенту"), formula: l("baza tarifată × tarif + majorări − reduceri", "тарифная база × тариф + надбавки − скидки"), example: l("10 kg × 34 Lei − 50 Lei = 290 Lei", "10 кг × 34 Lei − 50 Lei = 290 Lei") },
    { name: l("Sold partener", "Остаток партнёра"), formula: l("total datorat − total plătit", "начислено − оплачено"), example: l("1 200 − 900 = 300 Lei", "1 200 − 900 = 300 Lei") },
  ], notes: [l("FIFO consumă mai întâi marfa din cel mai vechi lot disponibil, la costul acelui lot.", "FIFO сначала списывает товар из самой старой доступной партии по её стоимости."), l("Subrețetele sunt desfăcute recursiv în rețeta principală.", "Подрецепты рекурсивно раскрываются в основном рецепте."), l("Valorile afișate sunt rotunjite; calculele interne pot păstra mai multe zecimale.", "Показанные значения округлены; внутренние расчёты могут хранить больше знаков.")] },
  { id: "probleme", icon: "problems", title: l("Probleme frecvente", "Частые проблемы"), summary: l("Citiți mesajul afișat și verificați câmpurile marcate. Simplul fapt că deschideți o fereastră nu schimbă stocul și nu șterge date.", "Прочитайте сообщение и проверьте отмеченные поля. Простое открытие окна не меняет запас и не удаляет данные."), steps: [l("Nu se salvează: verificați câmpurile obligatorii, numerele și data.", "Не сохраняется: проверьте обязательные поля, числа и дату."), l("Cost zero: verificați prețurile resurselor și rețeta.", "Нулевая стоимость: проверьте цены ресурсов и рецепт."), l("Stoc insuficient: verificați recepțiile sau micșorați cantitatea.", "Недостаточный запас: проверьте поступления или уменьшите количество."), l("Datele nu apar: verificați conexiunea și autentificați-vă din nou.", "Данные не видны: проверьте соединение и войдите снова."), l("Trimiteți administratorului textul exact al erorii și operația făcută.", "Передайте администратору точный текст ошибки и выполненную операцию.")] },
];

const icons = { start: BookOpen, dashboard: List, calculator: Calculator, recipes: ScrollText, lots: FileSpreadsheet, partners: Handshake, sales: ShoppingCart, stock: Warehouse, staff: Users, products: Package, reports: FileSpreadsheet, update: ShieldCheck, formulas: Calculator, problems: AlertTriangle };
const ui = {
  ro: { help: "Ajutor", title: "Manual de utilizare", subtitle: "Instrucțiuni clare, pas cu pas", search: "Caută în manual…", contents: "Cuprins", close: "Închide", empty: "Nu am găsit nicio secțiune.", hint: "Încercați: rețetă, lot, stoc sau vânzare.", steps: "Pașii de urmat", useful: "Bine de știut", attention: "Atenție", previous: "Înapoi", next: "Următoarea", example: "Exemplu", language: "Limba manualului", count: "secțiuni" },
  ru: { help: "Помощь", title: "Руководство пользователя", subtitle: "Понятные пошаговые инструкции", search: "Поиск в руководстве…", contents: "Содержание", close: "Закрыть", empty: "Разделы не найдены.", hint: "Попробуйте: рецепт, партия, склад или продажа.", steps: "Что нужно сделать", useful: "Полезно знать", attention: "Внимание", previous: "Назад", next: "Следующий", example: "Пример", language: "Язык руководства", count: "разделов" },
};

function Picture({ section, language }: { section: Section; language: Language }) {
  const pictures: Partial<Record<IconName, L[]>> = {
    calculator: [l("Alege rețeta", "Выберите рецепт"), l("Scrie cantitatea", "Введите количество"), l("Verifică rezultatul", "Проверьте результат")],
    recipes: [l("Componente", "Компоненты"), l("Cantități", "Количество"), l("Cost total", "Общая стоимость")],
    lots: [l("Intrare", "Вход"), l("Producție", "Производство"), l("Ieșire", "Выход")],
    sales: [l("Lot vechi", "Старая партия"), l("Vânzare FIFO", "Продажа FIFO"), l("Profit", "Прибыль")],
    formulas: [l("Date", "Данные"), l("Formulă", "Формула"), l("Rezultat", "Результат")],
  };
  const items = pictures[section.icon];
  if (!items) return null;
  return <div className="my-6 rounded-2xl border border-amber-500/30 bg-amber-50 p-4"><div className="flex flex-col items-stretch gap-2 sm:flex-row sm:items-center">{items.map((item, index) => <div className="contents" key={item.ro}><div className="flex min-h-20 flex-1 items-center gap-3 rounded-xl bg-stone-900 p-3 text-white shadow"><b className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-amber-500 text-stone-950">{index + 1}</b><span className="font-semibold">{tr(item, language)}</span></div>{index < items.length - 1 && <ChevronRight className="mx-auto h-6 w-6 rotate-90 text-amber-600 sm:rotate-0" />}</div>)}</div></div>;
}

function HelpModal({ onClose }: { onClose: () => void }) {
  const [language, setLanguage] = useState<Language>(() => localStorage.getItem("afumaturi-help-language") === "ru" ? "ru" : "ro");
  const [query, setQuery] = useState("");
  const [activeId, setActiveId] = useState(() => localStorage.getItem("afumaturi-help-section") || sections[0].id);
  const closeRef = useRef<HTMLButtonElement>(null);
  const copy = ui[language];
  useEffect(() => { const old = document.body.style.overflow; document.body.style.overflow = "hidden"; closeRef.current?.focus(); const escape = (e: KeyboardEvent) => e.key === "Escape" && onClose(); document.addEventListener("keydown", escape); return () => { document.body.style.overflow = old; document.removeEventListener("keydown", escape); }; }, [onClose]);
  const filtered = useMemo(() => { const needle = query.trim().toLocaleLowerCase(language); if (!needle) return sections; return sections.filter((s) => [s.title, s.summary, ...(s.steps || []), ...(s.notes || []), ...(s.formulas || []).flatMap((f) => [f.name, f.formula, f.example])].map((v) => tr(v, language)).join(" ").toLocaleLowerCase(language).includes(needle)); }, [language, query]);
  useEffect(() => { if (filtered.length && !filtered.some((s) => s.id === activeId)) setActiveId(filtered[0].id); }, [activeId, filtered]);
  const active = sections.find((s) => s.id === activeId) || sections[0]; const index = sections.findIndex((s) => s.id === active.id); const ActiveIcon = icons[active.icon];
  const select = (id: string) => { setActiveId(id); localStorage.setItem("afumaturi-help-section", id); };
  const changeLanguage = (next: Language) => { setLanguage(next); localStorage.setItem("afumaturi-help-language", next); };
  return <div className="fixed inset-0 z-[200] flex bg-black/75 backdrop-blur-sm sm:p-3 lg:p-6" onMouseDown={(e) => e.target === e.currentTarget && onClose()}>
    <section role="dialog" aria-modal="true" aria-labelledby="help-title" className="m-auto flex h-full w-full max-w-[1500px] flex-col overflow-hidden bg-stone-100 text-stone-900 shadow-2xl sm:h-[96vh] sm:rounded-2xl sm:border sm:border-stone-600">
      <header className="shrink-0 border-b border-stone-700 bg-stone-900 px-4 py-3 text-white sm:px-6"><div className="flex flex-wrap items-center gap-3">
        <div className="flex min-w-0 flex-1 items-center gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-amber-500 text-stone-950"><BookOpen /></span><div className="min-w-0"><h2 id="help-title" className="truncate text-lg font-black sm:text-2xl">{copy.title}</h2><p className="hidden text-sm text-stone-400 sm:block">{copy.subtitle}</p></div></div>
        <div className="order-3 flex w-full items-center gap-2 rounded-xl border border-stone-700 bg-stone-950 px-3 sm:order-none sm:w-[340px] lg:w-[420px]"><Search className="h-5 w-5 shrink-0 text-amber-500" /><label className="sr-only" htmlFor="help-search">{copy.search}</label><input id="help-search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder={copy.search} className="h-11 w-full bg-transparent text-base text-white outline-none placeholder:text-stone-500" />{query && <button onClick={() => setQuery("")} aria-label={copy.close}><X className="h-4 w-4" /></button>}</div>
        <div className="flex rounded-lg border border-stone-700 bg-stone-950 p-1" aria-label={copy.language}>{(["ro", "ru"] as Language[]).map((item) => <button key={item} onClick={() => changeLanguage(item)} className={`min-w-11 rounded-md px-2 py-2 text-sm font-black ${language === item ? "bg-amber-500 text-stone-950" : "text-stone-300 hover:bg-stone-800"}`} aria-pressed={language === item}>{item.toUpperCase()}</button>)}</div>
        <button ref={closeRef} onClick={onClose} className="flex h-11 items-center gap-2 rounded-lg border border-stone-700 px-3 font-semibold hover:border-red-500 hover:bg-red-950" aria-label={copy.close}><X className="h-5 w-5" /><span className="hidden xl:inline">{copy.close}</span></button>
      </div></header>
      <div className="flex min-h-0 flex-1 flex-col md:flex-row">
        <aside className="max-h-44 shrink-0 overflow-y-auto border-b border-stone-300 bg-stone-200 p-3 md:max-h-none md:w-72 md:border-b-0 md:border-r lg:w-80"><div className="mb-2 flex justify-between px-2"><h3 className="text-xs font-black uppercase tracking-widest text-stone-600">{copy.contents}</h3><span className="text-xs text-stone-500">{filtered.length} {copy.count}</span></div>{filtered.length ? <nav className="grid gap-1 sm:grid-cols-2 md:grid-cols-1">{filtered.map((s) => { const Icon = icons[s.icon]; const selected = s.id === active.id; return <button key={s.id} onClick={() => select(s.id)} className={`flex min-h-12 items-center gap-3 rounded-xl px-3 py-2 text-left text-sm font-semibold ${selected ? "bg-amber-500 text-stone-950 shadow" : "text-stone-700 hover:bg-white"}`} aria-current={selected ? "page" : undefined}><Icon className="h-5 w-5 shrink-0" /><span className="flex-1">{tr(s.title, language)}</span><ChevronRight className="h-4 w-4" /></button>; })}</nav> : <div className="p-5 text-center"><Search className="mx-auto h-8 w-8 text-stone-400" /><p className="mt-2 font-bold">{copy.empty}</p><p className="mt-1 text-sm text-stone-500">{copy.hint}</p></div>}</aside>
        <main className="min-h-0 flex-1 overflow-y-auto bg-stone-100" key={`${active.id}-${language}`}><article className="mx-auto max-w-5xl px-5 py-7 sm:px-8 sm:py-10 lg:px-12">
          <div className="mb-6 flex items-start gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-amber-500 text-stone-950 shadow"><ActiveIcon className="h-7 w-7" /></span><div><p className="mb-1 text-sm font-bold text-amber-700">{index + 1} / {sections.length}</p><h3 className="text-2xl font-black leading-tight sm:text-4xl">{tr(active.title, language)}</h3></div></div><p className="text-lg leading-8 text-stone-700 sm:text-xl">{tr(active.summary, language)}</p><Picture section={active} language={language} />
          {active.steps && <section className="mt-8"><h4 className="mb-4 flex items-center gap-2 text-xl font-black"><CheckCircle2 className="text-emerald-600" />{copy.steps}</h4><ol className="space-y-3">{active.steps.map((step, i) => <li key={step.ro} className="flex gap-4 rounded-xl border border-stone-300 bg-white p-4 shadow-sm"><b className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-stone-900 text-amber-400">{i + 1}</b><p className="pt-1 text-base leading-7 sm:text-lg">{tr(step, language)}</p></li>)}</ol></section>}
          {active.warning && <div className="mt-7 flex gap-4 rounded-xl border-2 border-red-300 bg-red-50 p-4 text-red-950"><AlertTriangle className="h-7 w-7 shrink-0 text-red-600" /><div><h4 className="font-black">{copy.attention}</h4><p className="mt-1 leading-7">{tr(active.warning, language)}</p></div></div>}
          {active.formulas && <div className="mt-8 grid gap-4 lg:grid-cols-2">{active.formulas.map((f) => <section key={f.name.ro} className="rounded-xl border border-stone-300 bg-white p-5 shadow-sm"><h4 className="text-lg font-black text-amber-700">{tr(f.name, language)}</h4><code className="my-3 block overflow-x-auto rounded-lg bg-stone-900 p-3 text-base font-bold text-amber-300">{tr(f.formula, language)}</code><p className="text-xs font-bold uppercase text-stone-500">{copy.example}</p><p className="mt-1 text-stone-700">{tr(f.example, language)}</p></section>)}</div>}
          {active.notes && <section className="mt-7 rounded-xl border border-blue-200 bg-blue-50 p-5"><h4 className="mb-3 flex items-center gap-2 text-lg font-black text-blue-950"><Lightbulb className="text-blue-600" />{copy.useful}</h4><ul className="space-y-3">{active.notes.map((note) => <li key={note.ro} className="flex gap-2 leading-7 text-blue-950"><span>•</span><span>{tr(note, language)}</span></li>)}</ul></section>}
          <footer className="mt-10 flex justify-between border-t border-stone-300 pt-6"><button disabled={index === 0} onClick={() => select(sections[index - 1].id)} className="flex min-h-11 items-center gap-2 rounded-lg border bg-white px-4 font-bold disabled:invisible"><ArrowLeft className="h-5 w-5" />{copy.previous}</button><button disabled={index === sections.length - 1} onClick={() => select(sections[index + 1].id)} className="flex min-h-11 items-center gap-2 rounded-lg bg-amber-500 px-4 font-bold text-stone-950 disabled:invisible">{copy.next}<ArrowRight className="h-5 w-5" /></button></footer>
        </article></main>
      </div>
    </section>
  </div>;
}

export default function HelpCenter({ mobile = false, onOpen }: { mobile?: boolean; onOpen?: () => void }) {
  const [open, setOpen] = useState(false); const language: Language = typeof window !== "undefined" && localStorage.getItem("afumaturi-help-language") === "ru" ? "ru" : "ro"; const label = ui[language].help;
  const show = () => { setOpen(true); onOpen?.(); };
  return <>{mobile ? <button type="button" onClick={show} className="flex w-full items-center space-x-3 rounded-md px-4 py-3 text-sm font-medium text-stone-300 hover:bg-stone-800 hover:text-amber-500"><CircleHelp className="h-5 w-5" /><span>{label}</span></button> : <button type="button" onClick={show} className="grid h-9 w-9 place-items-center rounded-lg border border-stone-800 text-stone-400 hover:border-amber-700 hover:bg-stone-800 hover:text-amber-500" title={label} aria-label={label}><CircleHelp className="h-5 w-5" /></button>}{open && <HelpModal onClose={() => setOpen(false)} />}</>;
}
